### ISSUE TITLE
[Creator] Create an API template based on OpenAPI Spec

### ISSUE THREAD

**Issue by miaojiang** [Azure/azure-api-management-devops-example#26]

**Comment by nzthiago** [comment]
A change from the original plan which was to perform the Open API to API Management conversion as part of this tool: As Azure API Management already supports the conversion from Open API spec, we are switching to embedding the OpenAPI file and policy files into an ARM template that the users can then deploy to Azure and the conversion will be done on the API Management side. This avoids duplication of effort between this tool and the APIM dev team
